import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// export function AppLayout() {
//   <div className="min-h-screen flex flex-col">
//       <main className="flex-grow bg-[#f7f7f7]">
    
//       </main>
//   </div>
// }


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col">
          <main className="flex-grow bg-[#f7f7f7]">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
