
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import CartProviderSetting from "./components/CartProviderSetting";
import Toasters from "./components/Toaster";
   
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "A-store",
  description: "Generated by create next app",
};

  

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}> 
       <CartProviderSetting>
          <div className="min-h-screen flex flex-col font-sans">
            <Header />
              <main className="flex-grow bg-[#f7f7f7]">
                {children}
                <Toasters />
              </main>
            <Footer />
          </div>
      </CartProviderSetting>
      </body>
    </html>
  );
}
